name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  schedule:
    - cron: '0 12 1 * *'

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checks-out repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v2

      - name: Setup Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'npm'

      # Install dependencies
      - run: npm install

      # Headless tests
      - run: npm run cy:run
        continue-on-error: true

      # Merges reports
      - run: npm run report:merge

      # Generates report
      - run: npm run report:mocha

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: mochawesome-report

      - name: Runs Cypress tests
        uses: cypress-io/github-action@v2
          
      - name: Upload a Build Artifact
        if: always()
        uses: actions/upload-artifact@v2.2.4
        with:
          path: cypress/videos